target-version = "py311"
line-length = 120
fix = true

[lint]
select = ["E", "W", "F", "I"]

[lint.per-file-ignores]
"backend/app/models/*" = ["E501", "E402"]
"backend/app/services/*" = ["E501", "E731", "E402", "E721"]
"backend/app/*" = ["E501", "E402"]
"backend/tests/*" = ["E501", "E402", "E741", "E712", "E721", "W293", "W292"]
"backend/tests/sandbox/*" = ["E501", "E402", "F402", "F811"]
"backend/*" = ["E501", "E402"]
"scripts/*" = ["E501", "E402", "E701", "W293", "W292"]
"diagnostics/*" = ["E501", "E402", "E741"]
"frontend/*" = ["E501", "E402", "W293"]
"build_graph.py" = ["E501"]