ai_model:
  model: qwen_7b
  path: Models LLM\Qwen2.5-7B-Instruct-abliterated-v2.Q5_K_M.gguf
audio:
  volume: 80
content:
  individual:
    profanity_level: 2
    sexual_content_level: 2
    taboo_practices_level: 2
    violence_level: 2
  last_changed_reason: user_action
  last_changed_tick: 0
  preset: explicit
controls:
  keybindings: {}
graphics:
  display_mode: windowed
  resolution:
    height: 1050
    width: 1680
interface:
  language: ru
performance:
  context_size: 8192
  temperature: 0.8
  workers: 2
